<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-942KJ2N" failures="2" tests="3" name="Test" time="68.357" errors="0" timestamp="2023-02-17T07:31:34 IST">
  <testcase classname="TestCases.VerifyLogin" name="login" time="0.127">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	url is not matching expected [https://login.salesfore.com/] but found [https://login.salesforce.com/]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
url is not matching expected [https://login.salesfore.com/] but found [https://login.salesforce.com/]
at PageObjectModel.commonMethod.AssertHandeling(commonMethod.java:25)
at TestCases.VerifyLogin.login(VerifyLogin.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="TestCases.VerifyLogin" name="login" time="0.057">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	url is not matching expected [https://login.salesfore.com/] but found [https://login.salesforce.com/]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
url is not matching expected [https://login.salesfore.com/] but found [https://login.salesforce.com/]
at PageObjectModel.commonMethod.AssertHandeling(commonMethod.java:25)
at TestCases.VerifyLogin.login(VerifyLogin.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="TestCases.VerifySinUp" name="Sinup" time="9.869"/>
</testsuite> <!-- Test -->
